changes to have "ervx build" subcommand work on both slurm and uge

diff --git a/resources/builder b/resources/builder
--- a/resources/builder
+++ b/resources/builder
@@ -121,6 +121,19 @@ function check(){
   done
 }
 
+function require(){
+  # Requires an executable is in $PATH, as a last resort it will attempt to load
+  # the executable or dependency as a module
+  # @INPUT $@ = List of dependencies or executables to check
+
+  for exe in "${@}"; do
+    # Check if executable is in $PATH
+    command -V ${exe} &> /dev/null && continue;
+    # Try to load exe as lua module
+    module load ${exe} &> /dev/null || \
+      fatal "Failed to find or load '${exe}', not installed on target system."
+  done
+}
 
 function submit(){
   # Submit jobs to the defined job scheduler or executor (i.e. slurm)
@@ -131,20 +144,10 @@ function submit(){
   # INPUT $5 = Singularity cache directory
   # INPUT $6 = Temporary directory for output files
 
-  # SLURM inherits the environment from which the job was launched
-  # Try to purge modules all modules from environment
-  command -V module &> /dev/null && module purge
-
-  # Check if singularity in $PATH
-  # If not, try to module load singularity as a last resort
-  command -V singularity &> /dev/null || module load singularity || \
-    fatal "Fail to find or load 'singularity', not installed on target system."
-
-  # Check if snakemake in $PATH
-  # If not, try to module load snakemake as a last resort
-  command -V snakemake &> /dev/null || module load snakemake || \
-    fatal "Fail to find or load 'snakemake', not installed on target system."
-
+  #Check if singularity and snakemake are in $PATH
+  # If not, try to module load singularity as a last resort  
+  require singularity snakemake
+  
   # Snakemake executor
   executor=${1}
 
@@ -178,20 +181,61 @@ function submit(){
           if [[ ${6#\'} != /lscratch* ]]; then
             CLUSTER_OPTS="sbatch --cpus-per-task {cluster.threads} -t {cluster.time} --mem {cluster.mem} --job-name={params.rname}"
           fi
-          # Submit the master job to the cluster
-          job_id=$(sbatch --parsable -J "$2" --time=4-00:00:00 --mail-type=BEGIN,END,FAIL \
-          --output "$3"/logfiles/snakemake.log --error "$3"/logfiles/snakemake.log \
-          snakemake --latency-wait 120 -s "$3"/workflow/rules/build.smk -d "$3" \
-            --use-singularity --singularity-args "'-B $4'" --configfile="$3"/config/build.yml \
-            --printshellcmds --cluster-config "$3"/resources/build_cluster.json \
-            --cluster "${CLUSTER_OPTS}" \
-            --keep-going --restart-times 3 -j 500 --rerun-incomplete --stats "$3"/logfiles/runtime_statistics.json \
-            --keep-remote 2>&1 | tee -a "$3"/logfiles/master.log)
-          # Clean-up working directory after completion
-          cleanup_id=$(sbatch -J "pl:clean" --dependency=afterany:${job_id} "$3"/resources/cleanup "$3" "$job_id")
+           # Create sbatch script for master job
+    cat << EOF > kickoff.sh
+#!/usr/bin/env bash
+#SBATCH --cpus-per-task=16 
+#SBATCH --mem=96g
+#SBATCH --time=5-00:00:00
+#SBATCH --parsable
+#SBATCH -J "$2"
+#SBATCH --mail-type=BEGIN,END,FAIL
+#SBATCH --output "$3/logfiles/snakemake.log"
+#SBATCH --error "$3/logfiles/snakemake.log"
+set -euo pipefail              
+
+snakemake --latency-wait 120 -s "$3"/workflow/rules/build.smk -d "$3" \\
+  --use-singularity --singularity-args "'-B $4'" --configfile="$3"/config/build.yml \\
+  --printshellcmds --cluster-config "$3"/resources/build_cluster_slurm.json \\
+  --cluster "${CLUSTER_OPTS}" \\
+  --keep-going --restart-times 3 -j 500 --rerun-incomplete --stats "$3"/logfiles/runtime_statistics.json \\
+  --keep-remote --local-cores 14 2>&1
+# Create summary report
+snakemake -d "$3" -s "$3/workflow/rules/build.smk" \\
+   --report "Snakemake_Report.html"
+EOF
+          chmod +x kickoff.sh
+          job_id=$(sbatch kickoff.sh | tee -a "$3"/logfiles/master.log)
+        ;;
+    uge)
+          # Create directory for logfiles
+          mkdir -p "$3/logfiles/ugefiles/"
+          UGE_DIR="$3/logfiles/ugefiles"
+          CLUSTER_OPTS="qsub -pe threaded {cluster.threads} {cluster.partition} -l h_vmem={cluster.mem} -N {params.rname} -o '$UGE_DIR/uge-\\\$JOB_ID-{params.rname}.out' -j y"
+          # Create qsub script for master job
+    cat << EOF > kickoff.sh
+#!/usr/bin/env bash
+#$ -pe threaded 16
+#$ -l h_vmem=6G
+#$ -N "$2"
+#$ -o "$3/logfiles/snakemake.log"
+#$ -j y
+set -euo pipefail
+snakemake --latency-wait 120 -s "$3"/workflow/rules/build.smk -d "$3" \\
+  --use-envmodules --use-singularity --singularity-args "'-B $4'" --configfile="$3"/config/build.yml \\
+  --printshellcmds --cluster-config "$3"/resources/build_cluster_uge.json \\
+  --cluster "${CLUSTER_OPTS}" \\
+  --keep-going --restart-times 3 -j 500 --rerun-incomplete --stats "$3"/logfiles/runtime_statistics.json \\
+  --keep-remote --local-cores 14 2>&1
+# Create summary report
+snakemake -d "$3" -s "$3/workflow/rules/build.smk" \\
+   --report "Snakemake_Report.html"
+EOF
+   chmod +x kickoff.sh
+    job_id=$(qsub -terse kickoff.sh | tee -a "$3"/logfiles/master.log)
         ;;
       *)  echo "${executor} is not available." && \
-          fatal "Failed to provide valid execution backend: ${executor}. Please use slurm."
+          fatal "Failed to provide valid execution backend: ${executor}. Please use slurm or uge."
         ;;
     esac
 
@@ -213,9 +257,10 @@ function main(){
   # Positional Argument for Snakemake Executor
   case $1 in
     slurm) Arguments["e"]="$1";;
+    uge) Arguments["e"]="$1";;
     -h    | --help | help) usage && exit 0;;
-    -*    | --*) err "Error: Failed to provide required positional argument: <slurm>."; usage && exit 1;;
-    *) err "Error: Failed to provide valid positional argument. '${1}' is not supported. Valid option(s) are slurm"; usage && exit 1;;
+    -*    | --*) err "Error: Failed to provide required positional argument: <slurm,uge>."; usage && exit 1;;
+    *) err "Error: Failed to provide valid positional argument. '${1}' is not supported. Valid option(s) are slurm or uge"; usage && exit 1;;
   esac
 
   # Parses remaining user provided command-line arguments
